# Generated by Django 5.0.6 on 2024-05-12 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_figma', '0002_management_structura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('character', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Electronic_Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.IntegerField()),
                ('keyword', models.CharField(max_length=250)),
                ('doc_category', models.CharField(max_length=250)),
                ('symbol', models.CharField(max_length=250)),
                ('doc_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=100)),
                ('e_mail', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=250)),
                ('comments', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('gmail', models.CharField(max_length=100)),
                ('gmail_2', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('managament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_figma.management')),
            ],
        ),
    ]
